obstacleDistance = [5 7 9 11 13 15];
load('line1.mat')
plot(obstacleDistance,timeArray)
hold on
title('Sight Range = 30')
axis([0 obstacleDistance(size(obstacleDistance,2))+5 20 max(timeArray)+20])
xlabel("Distance between obstacles")
ylabel("Time")
load('line2.mat')
plot(obstacleDistance,timeArray)
load('line3.mat')
plot(obstacleDistance,timeArray)
load('line4.mat')
plot(obstacleDistance,timeArray)
load('line5.mat')
plot(obstacleDistance,timeArray)
load('line6.mat')
plot(obstacleDistance,timeArray)
load('line7.mat')
plot(obstacleDistance,timeArray)
title(legend,'Number of Humans')
legend('10','15','20','25','30','35','40')